### ISSUE TITLE
fix: Hot reload always crashes on Static Mode after a syntax error is introduced at one point, even when it's fixed afterwards

### ISSUE THREAD

**Issue by dhafinrayhan** [schultek/jaspr#216] opened 2024-04-08 06:17 UTC
**Description**

When running development (`jaspr serve`) on **Static Mode**, hot reload always crashes and can't recover after at one point there's a syntax error in the code (even after the syntax error is fixed afterwards).

**Steps To Reproduce**

1. Create a new project using `jaspr create my_website`.
2. Choose `static` rendering mode (which should be the default).
3. Let other setup options with their default selections.
4. Run `jaspr serve`.
5. Open the page in a browser.
6. Introduce a syntax error. For example, you can add a component to the middle of a list without the mandatory separator comma:
    ```dart
    yield section([
      img(src: 'images/logo.png', width: 80),
      h1([text('Welcome')]),
      // Syntax error below (missing comma)
      Counter()
      p([text('You successfully create a new Jaspr site.')]),
      div(styles: Styles.box(height: 100.px), []),
      const Counter(),
    ]);
    ```
8. Notice that hot reload crashes, which is **expected**.
    ```
    [BUILDER] [ERROR] This builder requires Dart inputs without syntax errors.
    [BUILDER] [ERROR] However, package:jas_static/pages/home.dart (or an existing part) contains the following errors.
    [BUILDER] [ERROR] home.dart:16:7: Expected to find ','.
    [BUILDER] [ERROR]
    [BUILDER] [ERROR] Try fixing the errors and re-running the build.
    ```
10. Fix the syntax error (add comma after `Counter()`).
11. Notice that hot reload **still crashes**, even when there are no more syntax errors.
    ```
    [SERVER] [ERROR] ERROR - 2024-04-08 13:11:15.623075
    [SERVER] [ERROR] GET /
    [SERVER] [ERROR] Error thrown by handler.
    [SERVER] [ERROR] ClientException: HTTP request failed. Client is already closed., uri=http://localhost:5567/
    [SERVER] [ERROR] package:http/src/io_client.dart 110:7            IOClient.send
    [SERVER] [ERROR] package:shelf_proxy/shelf_proxy.dart 59:48       proxyHandler.<fn>
    [SERVER] [ERROR] package:shelf_gzip/src/gzip_encoding.dart 51:44  createGzipMiddleware.<fn>.<fn>.<fn>
    [SERVER] [ERROR] dart:async                                       new Future.sync
    [SERVER] [ERROR] package:shelf_gzip/src/gzip_encoding.dart 51:21  createGzipMiddleware.<fn>.<fn>
    [SERVER] [ERROR] ERROR - 2024-04-08 13:11:15.644062
    [SERVER] [ERROR] GET /favicon.ico
    ```
12. If you refresh the page on the browser, it will show you "Internal Server Error".

**Doctor Output**

```
[✓] Jaspr CLI (Version 0.11.1)
  • Dart Version 3.3.1 (stable) (Wed Mar 6 13:09:19 2024 +0000) on "windows_x64" at dart
  • Running on windows "Windows 10 Home Single Language" 10.0 (Build 22631) - Locale en-ID
  • Analytics: Enabled

[✓] Current Project
  • Dependencies on core packages:
    • jaspr: ^0.11.1
    • jaspr_builder: ^0.11.1 (dev)
    • jaspr_web_compilers: ^4.0.9 (dev)
    • jaspr_router: ^0.4.0
  • Rendering mode: static
  • Uses jaspr compilers: true
  • Uses flutter embedding: false

```

**Expected Behavior**

Hot reload should work normally after the syntax error is fixed.

**Additional Context**

This error does not happen when the project is running on **Server Mode**.

**Comment by schultek** [comment] 2024-04-11 07:06
There really is no difference between server and static mode when running ' jaspr serve'. 
I also cannot reproduce this reliably.

Are you using any other dependencies than the ones from the starting project?

**Comment by dhafinrayhan** [comment] 2024-04-11 07:17
No, there are no other dependencies, no other changes. The steps I did is exactly as mentioned above.

Yeah, I believe there should be no differences between the two, but apparently it always happens when I use Static Mode and does not happen in Server Mode somehow.

**Comment by schultek** [comment] 2024-04-11 19:14
Ok super weird, I can only reproduce this error when

1. I'm starting from a clean project (delete .dart_tool and run dart pub get)
2. I'm navigating to a different tab between step 5 and 6

Still no idea where the error comes from

**Comment by schultek** [comment] 2024-04-11 19:30
Ok I think I know now. A very hard race-condition inside the reloading logic

**Comment by schultek** [comment] 2024-04-11 19:52
@dhafinrayhan  Can you test if this is fixed with the following dependency override:

```yaml
dependency_overrides:
  jaspr:
    git:
      url: https://github.com/schultek/jaspr
      path: packages/jaspr
      ref: fix/reload-racecondition
```

**Comment by dhafinrayhan** [comment] 2024-04-12 00:43
Looking great! Seems like that fixes the issue.

**Closed** 2024-04-12 06:51 UTC
Labels: bug
