### ISSUE TITLE
fix: importing jaspr_markdown results in error in static mode

### ISSUE THREAD

**Issue by adriank** [schultek/jaspr#314] opened 2024-09-19 19:49 UTC
**Description**

I use Jaspr to build static website. When I integrated jaspr_markdown I got the following error on server console:

[BUILDER] [ERROR] org-dartlang-app:///packages/jaspr_markdown/src/component.dart:1:8: Error: Dart library 'dart:mirrors' is not available on this platform.

and this in browser:

ET http://localhost:8080/main.dart.js net::ERR_ABORTED 404 (Not Found)Understand this error
localhost/:1 Refused to execute script from 'http://localhost:8080/main.dart.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.

Reload/refresh stopped working.

jaspr_markdown doesn't support AOT, but I thought jaspr serve is running in JIT? 

**Steps To Reproduce**

Create project in static mode. Add jaspr_markdown. Include it in app.dart.

**Doctor Output**

All is ok

**Expected Behavior**

Reload/refresh works.

**Additional Context**

BTW. Somehow my project stopped refreshing even after completely removing jaspr_markdown. I had to recreate it from scratch. Cleaning, deleting .build and .dart_tool didn't help.

**Comment by schultek** [comment] 2024-09-28 19:38
You are right that the server runs with jit, but this error comes from compiling the app to js for the client side execution.

You probably need to use conditional imports for this or this: https://docs.page/schultek/jaspr/utils/at_import

**Comment by adriank** [comment] 2024-09-28 21:11
I want to build something like very simplified Docusaurus on top of Jaspr, but without jaspr_markdown working in static website mode, I think it's impossible. At least debug mode is not possible ATM. Am I right?

I tried both and I have a bunch of errors:

```
@Import.onWeb('package:jaspr_markdown', show: [#Markdown])
import 'markdown.imports.dart';
```
Running jaspr in static rendering mode.
[BUILDER] [ERROR] Unable to find modules for some sources, this is usually the result of either a
[BUILDER] [ERROR] bad import, a missing dependency in a package (or possibly a dev_dependency
[BUILDER] [ERROR] needs to move to a real dependency), or a build failure (if importing a
[BUILDER] [ERROR] generated file).

```
@Import.onServer('package:jaspr_markdown', show: [#Markdown])
import 'markdown.imports.dart';
```

_vm.dart:
import 'package:jaspr_markdown' show Markdown; **<-- can't find package**
export 'package:jaspr_markdown' show Markdown;

typedef MarkdownOrStubbed = Markdown;

**Comment by schultek** [comment] 2024-09-28 21:18
Has to be a valid import still: `'package:jaspr_markdown/jaspr_markdown.dart'`

**Comment by adriank** [comment] 2024-09-28 21:27
Now no errors on server, but unfortunately in browser I get:

Error: TypeError: Cannot read properties of null (reading 'name') dart:sdk_internal 9706:69                                    dcall
package:plyn_jaspr/components/markdown.dart 15:15            build
dart:sdk_internal 24619:30                                   toList
package:jaspr/src/framework/buildable_element.dart 52:23     performRebuild
package:jaspr/src/framework/stateless_component.dart 179:11  performRebuild
package:jaspr/src/framework/build_owner.dart 85:27           performRebuildOn
package:jaspr/src/framework/framework.dart 998:5             rebuild
package:jaspr/src/framework/buildable_element.dart 34:5      didMount
package:jaspr/src/framework/stateless_component.dart 161:11  didMount
package:jaspr/src/framework/framework.dart 652:13            inflateComponent
package:jaspr/src/framework/framework.dart 318:18            updateChild
package:jaspr/src/framework/framework.dart 384:22            updateChildren
package:jaspr/src/framework/buildable_element.dart 72:17     performRebuild
package:jaspr/src/framework/stateless_component.dart 179:11  performRebuild
package:jaspr/src/framework/build_owner.dart 85:27           performRebuildOn
package:jaspr/src/framework/framework.dart 998:5             rebuild
package:jaspr/src/framework/buildable_element.dart 34:5      didMount
package:jaspr/src/framework/stateless_component.dart 161:11  didMount
package:jaspr/src/framework/framework.dart 652:13            inflateComponent
package:jaspr/src/framework/framework.dart 318:18            updateChild
package:jaspr/src/framework/framework.dart 384:22            updateChildren
package:jaspr/src/framework/proxy_element.dart 61:17         performRebuild
package:jaspr/src/framework/build_owner.dart 85:27           performRebuildOn
package:jaspr/src/framework/framework.dart 998:5             rebuild
package:jaspr/src/framework/proxy_element.dart 45:5          didMount
package:jaspr/src/framework/framework.dart 652:13            inflateComponent
package:jaspr/src/framework/framework.dart 318:18            updateChild
package:jaspr/src/framework/framework.dart 471:32            updateChildren
package:jaspr/src/framework/proxy_element.dart 61:17         performRebuild
package:jaspr/src/framework/build_owner.dart 85:27           performRebuildOn
package:jaspr/src/framework/framework.dart 998:5             rebuild
package:jaspr/src/framework/proxy_element.dart 45:5          didMount
package:jaspr/src/framework/framework.dart 652:13            inflateComponent
package:jaspr/src/framework/framework.dart 318:18            updateChild
package:jaspr/src/framework/framework.dart 384:22            updateChildren
package:jaspr/src/framework/buildable_element.dart 72:17     performRebuild
package:jaspr/src/framework/stateless_component.dart 179:11  performRebuild
package:jaspr/src/framework/build_owner.dart 85:27           performRebuildOn
package:jaspr/src/framework/framework.dart 998:5             rebuild
package:jaspr/src/framework/buildable_element.dart 34:5      didMount
package:jaspr/src/framework/stateless_component.dart 161:11  didMount
package:jaspr/src/framework/framework.dart 652:13            inflateComponent
package:jaspr/src/framework/framework.dart 318:18            updateChild
package:jaspr/src/framework/framework.dart 384:22            updateChildren
package:jaspr/src/framework/proxy_element.dart 61:17         performRebuild
package:jaspr/src/framework/build_owner.dart 85:27           performRebuildOn
package:jaspr/src/framework/framework.dart 998:5             rebuild
package:jaspr/src/framework/proxy_element.dart 45:5          didMount
package:jaspr/src/framework/framework.dart 652:13            inflateComponent
package:jaspr/src/framework/framework.dart 318:18            updateChild
package:jaspr/src/framework/framework.dart 384:22            updateChildren
package:jaspr/src/framework/proxy_element.dart 61:17         performRebuild
package:jaspr/src/framework/build_owner.dart 85:27           performRebuildOn
package:jaspr/src/framework/framework.dart 998:5             rebuild
package:jaspr/src/framework/proxy_element.dart 45:5          didMount
package:jaspr/src/framework/framework.dart 652:13            inflateComponent
package:jaspr/src/framework/framework.dart 318:18            updateChild
package:jaspr/src/framework/framework.dart 471:32            updateChildren
package:jaspr/src/framework/buildable_element.dart 72:17     performRebuild
package:jaspr/src/framework/stateful_component.dart 693:11   performRebuild
package:jaspr/src/framework/build_owner.dart 85:27           performRebuildOn
package:jaspr/src/framework/framework.dart 998:5             rebuild
package:jaspr/src/framework/buildable_element.dart 34:5      didMount
package:jaspr/src/framework/stateful_component.dart 649:11   didMount
package:jaspr/src/framework/framework.dart 652:13            inflateComponent
package:jaspr/src/framework/framework.dart 318:18            updateChild
package:jaspr/src/framework/framework.dart 384:22            updateChildren
package:jaspr/src/framework/proxy_element.dart 61:17         performRebuild
package:jaspr/src/framework/build_owner.dart 85:27           performRebuildOn
package:jaspr/src/framework/framework.dart 998:5             rebuild
package:jaspr/src/framework/proxy_element.dart 45:5          didMount
package:jaspr/src/framework/render_object.dart 49:11         didMount
package:jaspr/src/framework/render_object.dart 28:16         didMount
package:jaspr/src/framework/framework.dart 652:13            inflateComponent
package:jaspr/src/framework/framework.dart 318:18            updateChild
package:jaspr/src/framework/framework.dart 471:32            updateChildren
package:jaspr/src/framework/buildable_element.dart 72:17     performRebuild
package:jaspr/src/framework/stateful_component.dart 693:11   performRebuild
package:jaspr/src/framework/build_owner.dart 85:27           performRebuildOn
package:jaspr/src/framework/framework.dart 998:5             rebuild
package:jaspr/src/framework/buildable_element.dart 34:5      didMount
package:jaspr/src/framework/stateful_component.dart 649:11   didMount
package:jaspr/src/framework/framework.dart 652:13            inflateComponent
package:jaspr/src/framework/framework.dart 318:18            updateChild
package:jaspr/src/framework/framework.dart 384:22            updateChildren
package:jaspr/src/framework/buildable_element.dart 72:17     performRebuild
package:jaspr/src/framework/stateless_component.dart 179:11  performRebuild
package:jaspr/src/framework/build_owner.dart 85:27           performRebuildOn
package:jaspr/src/framework/framework.dart 998:5             rebuild
package:jaspr/src/framework/buildable_element.dart 34:5      didMount
package:jaspr/src/framework/stateless_component.dart 161:11  didMount
package:jaspr/src/framework/framework.dart 652:13            inflateComponent
package:jaspr/src/framework/framework.dart 318:18            updateChild
package:jaspr/src/framework/framework.dart 384:22            updateChildren
package:jaspr/src/framework/proxy_element.dart 61:17         performRebuild
package:jaspr/src/framework/build_owner.dart 85:27           performRebuildOn
package:jaspr/src/framework/framework.dart 998:5             rebuild
package:jaspr/src/framework/proxy_element.dart 45:5          didMount
package:jaspr/src/framework/render_object.dart 49:11         didMount
package:jaspr/src/framework/render_object.dart 28:16         didMount
package:jaspr/src/framework/build_owner.dart 14:12           performInitialBuild
dart:sdk_internal 41725:7                                    _async
package:jaspr/src/framework/build_owner.dart 12:35           performInitialBuild
package:jaspr/src/framework/components_binding.dart 20:23    <fn>
dart:sdk_internal 41725:7                                    _async
package:jaspr/src/framework/components_binding.dart 8:32     <fn>
package:jaspr/src/framework/build_owner.dart 67:25           lockState
dart:sdk_internal 41725:7                                    _async
package:jaspr/src/framework/build_owner.dart 60:25           lockState
package:jaspr/src/framework/components_binding.dart 8:21     attachRootComponent
dart:sdk_internal 41725:7                                    _async
package:jaspr/src/framework/components_binding.dart 6:35     attachRootComponent
package:jaspr/src/browser/browser_binding.dart 38:18         attachRootComponent
package:jaspr/src/browser/run_app.dart 6:31                  <fn>
package:jaspr/src/browser/run_app.dart 6:74                  runApp
main.dart 12:3                                               main$
main.dart.bootstrap.js 296:10                                <fn>
main.dart.bootstrap.js 295:32                                $dartRunMain
%3Canonymous%3E 1:8                                          <fn>
dwds/src/injected/client.js 9908:21                          runMain
dwds/src/injected/client.js 26172:19                         <fn>
dwds/src/injected/client.js 4060:15                          $protected
dwds/src/injected/client.js 12486:12                         call$2
dwds/src/injected/client.js 4024:20                          _asyncStartSync
dwds/src/injected/client.js 26188:16                         $call$body$main__closure
dwds/src/injected/client.js 26101:19                         call$1
dwds/src/injected/client.js 4443:16                          _rootRunUnary
dwds/src/injected/client.js 13881:39                         runUnary$2$2
dwds/src/injected/client.js 13828:14                         runUnaryGuarded$1$2
dwds/src/injected/client.js 13421:19                         _sendData$1
dwds/src/injected/client.js 13604:59                         perform$1
dwds/src/injected/client.js 13663:14                         call$0
dwds/src/injected/client.js 4283:24                          _microtaskLoop
dwds/src/injected/client.js 4289:11                          _startMicrotaskLoop
dwds/src/injected/client.js 12363:9                          call$1

**Comment by schultek** [comment] 2024-09-29 10:00
Check if you are using kIsWeb as described in the docs.

If you having futher problems please ask in discord in the code-review channel. I'm going to close this as its not a bug in the framework.

**Closed by schultek** 2024-09-29 10:00 UTC
Labels: bug

**Comment by adriank** [comment] 2024-09-29 12:29
Doing this:

```
import 'package:jaspr/jaspr.dart';

@Import.onServer('package:jaspr_markdown/jaspr_markdown.dart', show: [#Markdown])
import 'markdown.imports.dart';

class MarkdownComponent extends StatelessComponent {
  const MarkdownComponent({
    required this.markdown,
    super.key,
  });

  final String markdown;

  @override
  Iterable<Component> build(BuildContext context) sync* {
    if (!kIsWeb) {
      yield section([
        Markdown(
          markdown: markdown,
        ),
      ]);
    }
  }
}
```

Initially renders markdown correctly, but immediately after content is replaced with frontend code.

If that's not a bug, then it's a feature request. :)

**Comment by schultek** [comment] 2024-09-30 07:56
Well its doing what the code tells it. On the server it renders the markdown comp, on the client it renders nothing.

If you just want to statically render this on the server this probably doesn't even need to be hydrated on the client. Check the docs how to do that.
